name: '${project.build.finalName}'
version: '${project.version}'
api-version: '1.20'
main: dev.better.trees.Core
author: deathibring
description: An alternate take on woodcutting and tree population.
commands:
  addtreelocation:
    description: Generate a tree and save its location.